name = "v20251104"
main = "_worker.js"
compatibility_date = "2025-11-04"
keep_vars = true

#[[kv_namespaces]]
#binding = "hexo"			#KV绑定名默认不可修改
#id = "ab3f3ab4a4a24eeca0410928f3db0eec"				#KV数据库id